leaf.name=com.sankuai.leaf.opensource.test
#leaf.segment.enable=false
leaf.segment.enable=true
leaf.jdbc.url=jdbc:mysql://127.0.0.1:3306/leaf?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
leaf.jdbc.username=root
leaf.jdbc.password=062690

leaf.snowflake.enable=false
#leaf.snowflake.enable=true
leaf.snowflake.zk.address=192.168.170.142:2181
#snowflake ????????
leaf.snowflake.port=2222