elasticsearch:
  address: 192.168.170.142:9200 # Elasticsearch 地址
  hotUpdateExtDict: D:\Work\Work_on_JAVA\__lib\elasticsearch-analysis-ik-7.12.1\config\custom\mydict_hot_update.dic

canal: # Canal 配置
  address: 192.168.170.142:11111 # 链接地址
  destination: example # 数据目标
  username: canal # 数据库用户名
  password: 062690 # 数据库密码
  subscribe: mybook.note,mybook.user # 订阅规则，只订阅笔记表和用户表
  batchSize: 1000 # 一批次拉取数据量
